<?php
$e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$methodLabel = $allocation->disbursement_method === 'RTGS' ? 'Bank Transfer / RTGS' : 'Cheque / SLIPS';
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Allocation Receipt - <?= $e($allocation->reference_no) ?></title>
  <style>
    * { box-sizing: border-box; }
    body { margin: 0; padding: 40px 20px; background: #f5f7fb; color: #111827; font-family: Arial, sans-serif; }
    .receipt { max-width: 780px; margin: 0 auto; overflow: hidden; border: 1px solid #dfe3ec; border-radius: 12px; background: #fff; box-shadow: 0 12px 35px rgba(15,23,42,.08); }
    .strip { height: 7px; background: #3154d8; }
    header, main, footer { padding: 28px 32px; }
    header { display: flex; justify-content: space-between; gap: 24px; border-bottom: 1px dashed #cbd5e1; }
    h1 { margin: 0 0 6px; color: #2444bd; font-size: 22px; }
    h2 { margin: 0 0 13px; font-size: 14px; }
    p { margin: 0; color: #64748b; font-size: 12px; line-height: 1.55; }
    .ref { display: inline-block; padding: 7px 11px; border-radius: 7px; background: #eef2ff; color: #2444bd; font-size: 13px; font-weight: 700; }
    .status { display: block; margin-top: 7px; color: #15803d; font-size: 11px; font-weight: 700; text-align: right; }
    .amount { display: flex; justify-content: space-between; gap: 20px; align-items: center; padding: 22px 32px; background: #f8fafc; }
    .amount span { color: #64748b; font-size: 10px; font-weight: 700; letter-spacing: .08em; text-transform: uppercase; }
    .amount strong { display: block; margin-top: 5px; color: #2444bd; font-size: 26px; }
    .amount time { color: #475569; font-size: 12px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 18px; }
    .card { padding: 17px; border: 1px solid #e5e7eb; border-radius: 9px; }
    dl { margin: 0; }
    dl div { display: flex; justify-content: space-between; gap: 16px; padding: 7px 0; border-bottom: 1px solid #f1f5f9; font-size: 11px; }
    dl div:last-child { border: 0; }
    dt { color: #64748b; } dd { margin: 0; font-weight: 700; text-align: right; }
    .purpose { margin-top: 18px; }
    .purpose p { padding: 14px; border-radius: 8px; background: #f8fafc; color: #334155; }
    footer { display: flex; align-items: center; justify-content: space-between; gap: 20px; border-top: 1px solid #e5e7eb; background: #f8fafc; }
    button { min-height: 40px; padding: 0 16px; border: 0; border-radius: 8px; background: #3154d8; color: #fff; font-weight: 700; cursor: pointer; }
    @media (max-width: 640px) { header, .amount, footer { align-items: flex-start; flex-direction: column; } .grid { grid-template-columns: 1fr; } .status { text-align: left; } }
    @media print { body { padding: 0; background: #fff; } .receipt { border: 0; box-shadow: none; } .no-print { display: none; } }
  </style>
</head>
<body>
  <article class="receipt">
    <div class="strip"></div>
    <header>
      <div><h1>National Youth Services Council</h1><p><?= $e($allocation->division_name) ?> Division<br>Official Club Fund Allocation Receipt</p></div>
      <div><span class="ref"><?= $e($allocation->reference_no) ?></span><span class="status"><?= $e($allocation->status) ?></span></div>
    </header>
    <section class="amount"><div><span>Allocation amount</span><strong>Rs. <?= number_format((float) $allocation->amount, 2) ?></strong></div><time><?= $e(date('d M Y, H:i', strtotime($allocation->created_at))) ?></time></section>
    <main>
      <div class="grid">
        <section class="card"><h2>Recipient and allocation</h2><dl><div><dt>Club</dt><dd><?= $e($allocation->club_name) ?></dd></div><div><dt>Category</dt><dd><?= $e($allocation->fund_category ?: 'Uncategorised') ?></dd></div><div><dt>Transfer date</dt><dd><?= $e(date('d M Y', strtotime($allocation->transfer_date))) ?></dd></div><div><dt>Reference</dt><dd><?= $e($allocation->reference_no) ?></dd></div></dl></section>
        <section class="card"><h2>Settlement and authorization</h2><dl><div><dt>Method</dt><dd><?= $e($methodLabel) ?></dd></div><div><dt>Source bank</dt><dd><?= $e($allocation->bank_name ?: 'Not recorded') ?></dd></div><div><dt>Account</dt><dd><?= $e($allocation->account_number ?: 'Not recorded') ?></dd></div><div><dt>Authorized by</dt><dd><?= $e(trim((string) $allocation->authorized_by_name) ?: 'Divisional Treasurer') ?></dd></div></dl></section>
      </div>
      <section class="card purpose"><h2>Purpose and description</h2><p><?= nl2br($e($allocation->purpose_description)) ?></p></section>
    </main>
    <footer><p>Generated by YouthNexus &bull; Divisional Financial Management</p><button class="no-print" type="button" onclick="window.print()">Print / Save PDF</button></footer>
  </article>
</body>
</html>
