<?php
require_once __DIR__ . '/../partials/icons.view.php';
$e = static fn($value) => htmlspecialchars((string) $value, ENT_QUOTES, 'UTF-8');
$title = 'Report Preview - YouthNexus';
$pageTitle = 'Report Preview';
$pageDescription = $report->type_name;
$currentRoute = 'divisionalreports';
$pageStyles = [ROOT . '/assets/css/divisional-workflows.css', ROOT . '/assets/css/divisional-reports.css'];
$pageScripts = [ROOT . '/assets/js/divisional-workflows.js', ROOT . '/assets/js/divisional-reports.js'];
require __DIR__ . '/../layouts/dashboard-start.view.php';
?>
<section class="dw-page dr-preview" aria-label="Report preview">
  <div class="dr-preview__actions"><a class="dw-button dw-button--secondary" href="<?= ROOT ?>/divisionalreports">Back to Reports</a><a class="dw-button dw-button--secondary" href="<?= ROOT ?>/divisionalreports/export/<?= (int) $report->report_id ?>"><?= yn_icon('download') ?> Download CSV</a><a class="dw-button dw-button--primary" href="<?= ROOT ?>/divisionalreports/pdf/<?= (int) $report->report_id ?>"><?= yn_icon('download') ?> Download PDF</a></div>
  <article class="dw-panel dr-document">
    <header class="dr-document__header"><div><span>YouthNexus</span><h2><?= $e($report->type_name) ?></h2><p><?= $e($division->division_name) ?></p></div><div class="dr-document__reference"><strong>RPT-<?= str_pad((string) $report->report_id, 4, '0', STR_PAD_LEFT) ?></strong><span><?= $e(date('d M Y, H:i', strtotime($report->generated_at))) ?></span></div></header>
    <dl class="dr-meta"><div><dt>Reporting period</dt><dd><?= $e(date('d M Y', strtotime($report->date_range_start))) ?> - <?= $e(date('d M Y', strtotime($report->date_range_end))) ?></dd></div><div><dt>Category</dt><dd><?= $e($report->category) ?></dd></div><div><dt>Generated by</dt><dd><?= $e(trim((string) $report->generated_by_name) ?: 'Divisional Treasurer') ?></dd></div><div><dt>Scope</dt><dd>Divisional</dd></div></dl>
    <div class="dr-kpi-grid"><?php foreach ($reportData['kpis'] as $kpi): ?><div class="dr-kpi"><span><?= $e($kpi['label']) ?></span><strong><?= $e($kpi['value']) ?></strong></div><?php endforeach; ?></div>
    <section class="dr-results"><h3>Report Details</h3><div class="dw-table-wrap"><table class="dw-table"><thead><tr><?php foreach ($reportData['columns'] as $label): ?><th><?= $e($label) ?></th><?php endforeach; ?></tr></thead><tbody><?php foreach ($reportData['rows'] as $row): ?><tr><?php foreach (array_keys($reportData['columns']) as $key): ?><td><?= $e($row[$key] ?? '-') ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php if (!$reportData['rows']): ?><div class="dw-empty-state is-visible"><span class="dw-empty-state__icon"><?= yn_icon('file') ?></span><strong>No records found</strong><p>No matching records were recorded during this reporting period.</p></div><?php endif; ?></section>
    <footer class="dr-document__footer"><span>Generated from YouthNexus records</span><span><?= $e($division->division_name) ?></span></footer>
  </article>
  <form class="dr-archive" method="post" action="<?= ROOT ?>/divisionalreports/archive/<?= (int) $report->report_id ?>" onsubmit="return confirm('Archive this report?');"><input type="hidden" name="csrf_token" value="<?= $e($csrfToken) ?>"><button class="dw-button dw-button--danger" type="submit">Archive Report</button></form>
</section>
<?php require __DIR__ . '/../layouts/dashboard-end.view.php'; ?>
