<?php
$escape = static function ($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); };
require __DIR__ . '/../partials/icons.view.php';
require __DIR__ . '/../layouts/dashboard-start.view.php';
?>

<section class="club-page" aria-labelledby="zonal-ledger-heading">
    <h1 id="zonal-ledger-heading" class="sr-only">Zonal ledger</h1>
    <?php if ($flash): ?><div class="club-error-banner" role="status"><span class="club-error-icon"><?= yn_icon('info') ?></span><p><?= $escape($flash) ?></p></div><?php endif; ?>
    <div class="club-stat-grid"><article class="club-stat-card"><p class="club-stat-label">Running balance</p><p class="club-stat-value club-stat-value--small">LKR <?= number_format($balance, 2) ?></p></article><article class="club-stat-card"><p class="club-stat-label">Recorded income</p><p class="club-stat-value club-stat-value--small">LKR <?= number_format($income, 2) ?></p></article><article class="club-stat-card"><p class="club-stat-label">Recorded expenses</p><p class="club-stat-value club-stat-value--small">LKR <?= number_format($expenses, 2) ?></p></article></div>
    <section class="club-panel" aria-labelledby="zonal-ledger-list-heading"><div class="club-panel-header"><div><p class="club-eyebrow">Gampaha Zone</p><h2 id="zonal-ledger-list-heading">Transaction ledger</h2></div><div class="club-event-side"><a class="club-btn-secondary" href="<?= ROOT ?>/zonaltreasurer/exportzonalledger"><?= yn_icon('download') ?> Export</a><button class="club-btn-primary" type="button" data-open="log-transaction">Log transaction</button></div></div><p class="club-muted">Session-only records with running balances. Division allocations are recorded through the allocation workflow.</p>
    <div class="club-table-wrap"><table class="club-table"><thead><tr><th>Date</th><th>Description</th><th>Type</th><th>Amount</th><th>Balance</th><th>Receipt</th><th>Status</th></tr></thead><tbody><?php foreach ($entries as $entry): ?><tr><td><?= $escape($entry['date']) ?></td><td><?= $escape($entry['description']) ?></td><td><span class="club-pill club-pill--<?= $escape($entry['type_key']) ?>"><?= $escape($entry['type']) ?></span></td><td>LKR <?= number_format($entry['amount'], 2) ?></td><td>LKR <?= number_format($entry['balance'], 2) ?></td><td><?= $escape($entry['receipt']) ?></td><td><span class="club-pill club-pill--<?= $escape($entry['status_key']) ?>"><?= $escape($entry['status']) ?></span></td></tr><?php endforeach; ?></tbody></table></div></section>
</section>
<div id="log-transaction" class="popup-overlay" hidden><div class="popup-content club-modal" role="dialog" aria-modal="true" aria-labelledby="log-title"><button type="button" class="popup-close" data-close aria-label="Close"><?= yn_icon('close') ?></button><p class="club-eyebrow">Zonal Treasurer action</p><h2 id="log-title">Log transaction</h2><form method="post" action="<?= ROOT ?>/zonaltreasurer/logtransaction" class="club-form"><input type="hidden" name="csrf_token" value="<?= $escape($csrf_token) ?>"><div class="club-form-grid"><div class="club-field"><label for="ledger-type">Transaction type</label><select id="ledger-type" name="type"><option>Income</option><option>Expense</option></select></div><div class="club-field"><label for="ledger-amount">Amount (LKR)</label><input id="ledger-amount" name="amount" type="number" min="0.01" step="0.01" required></div><div class="club-field"><label for="ledger-date">Date</label><input id="ledger-date" name="transaction_date" type="date" required></div><div class="club-field"><label for="ledger-receipt">Receipt reference</label><input id="ledger-receipt" name="receipt" maxlength="100" required></div><div class="club-field club-field--full"><label for="ledger-description">Description</label><input id="ledger-description" name="description" maxlength="255" required></div></div><div class="club-modal-footer"><button type="button" class="club-btn-secondary" data-close>Cancel</button><button type="submit" class="club-btn-primary">Record transaction</button></div></form></div></div>
<script>document.querySelector('[data-open="log-transaction"]').addEventListener('click',()=>{document.getElementById('log-transaction').hidden=false;});document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>{button.closest('.popup-overlay').hidden=true;}));</script>
<link rel="stylesheet" href="<?= ROOT ?>/assets/css/club.css">
<?php require __DIR__ . '/../layouts/dashboard-end.view.php'; ?>
