<?php
$escape = static function ($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); };
require __DIR__ . '/../partials/icons.view.php';
require __DIR__ . '/../layouts/dashboard-start.view.php';
?>

<section class="club-page" aria-labelledby="zonal-voids-heading">
    <h1 id="zonal-voids-heading" class="sr-only">Division void requests</h1>
    <?php if ($flash): ?><div class="club-error-banner" role="status"><span class="club-error-icon"><?= yn_icon('info') ?></span><p><?= $escape($flash) ?></p></div><?php endif; ?>
    <div class="club-stat-grid"><article class="club-stat-card"><p class="club-stat-label">Pending review</p><p class="club-stat-value"><?= $escape($pendingCount) ?></p></article><article class="club-stat-card"><p class="club-stat-label">Queue scope</p><p class="club-stat-value club-stat-value--small">3 divisions</p></article></div>
    <section class="club-panel" aria-labelledby="zonal-void-queue-heading">
        <div class="club-panel-header"><div><p class="club-eyebrow">Gampaha Zone</p><h2 id="zonal-void-queue-heading">Division void request queue</h2></div><a class="club-btn-secondary" href="<?= ROOT ?>/zonaltreasurer/exportvoids"><?= yn_icon('download') ?> Export</a></div>
        <p class="club-muted">Only division-originated requests appear here. Club requests are reviewed at the divisional tier.</p>
        <form method="get" action="<?= ROOT ?>/zonaltreasurer/voids" class="club-filters" role="search" aria-label="Filter void requests"><label class="club-search"><span class="icon"><?= yn_icon('eye') ?></span><span class="sr-only">Search requests</span><input type="search" name="search" value="<?= $escape($search) ?>" placeholder="Search division or reference"></label><label class="club-filter-field"><span class="sr-only">Status</span><select name="status"><option value="Pending" <?= $status === 'Pending' ? 'selected' : '' ?>>Pending</option><option value="Approved" <?= $status === 'Approved' ? 'selected' : '' ?>>Approved</option><option value="Rejected" <?= $status === 'Rejected' ? 'selected' : '' ?>>Rejected</option><option value="" <?= $status === '' ? 'selected' : '' ?>>All statuses</option></select></label><button type="submit" class="club-btn-secondary">Apply filters</button></form>
        <div class="club-table-wrap"><table class="club-table"><thead><tr><th>Division</th><th>Transaction</th><th>Amount</th><th>Requested</th><th>Reason</th><th>Status</th><th>Action</th></tr></thead><tbody><?php foreach ($requests as $request): ?><tr><td><strong><?= $escape($request['division']) ?></strong><br><span class="club-asset-id"><?= $escape($request['id']) ?></span></td><td><?= $escape($request['description']) ?><br><span class="club-asset-id"><?= $escape($request['reference']) ?></span></td><td>LKR <?= number_format($request['amount'], 2) ?></td><td><?= $escape($request['requested_on']) ?></td><td><?= $escape($request['reason']) ?></td><td><span class="club-pill club-pill--<?= strtolower($request['status']) === 'pending' ? 'pending' : 'verified' ?>"><?= $escape($request['status']) ?></span></td><td><?php if ($request['status'] === 'Pending'): ?><button type="button" class="club-btn-small" data-review="<?= $escape($request['id']) ?>" data-division="<?= $escape($request['division']) ?>" data-reference="<?= $escape($request['reference']) ?>">Review</button><?php elseif (!empty($request['remark'])): ?><span class="club-note"><?= $escape($request['remark']) ?></span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
        <?php if (!$requests): ?><p class="club-note">No division void requests match these filters.</p><?php endif; ?>
    </section>
</section>

<div id="void-review" class="popup-overlay" hidden><div class="popup-content club-modal" role="dialog" aria-modal="true" aria-labelledby="void-review-title"><button type="button" class="popup-close" data-close aria-label="Close"><?= yn_icon('close') ?></button><p class="club-eyebrow">Zonal Treasurer decision</p><h2 id="void-review-title">Review void request</h2><p id="void-review-reference" class="club-sub-note"></p><form id="void-decision-form" method="post" class="club-form"><input type="hidden" name="csrf_token" value="<?= $escape($csrf_token) ?>"><input id="void-review-id" type="hidden" name="void_id"><div class="club-field"><label for="void-remark">Decision remark</label><textarea id="void-remark" name="remark" rows="4" maxlength="1000" required></textarea></div><div class="club-impact" role="note"><strong>Decision effect</strong><p>Approval voids the requested divisional transaction in the future backend. Rejection leaves it unchanged. The division receives the decision remark.</p></div><div class="club-modal-footer"><button type="button" class="club-btn-secondary" data-close>Cancel</button><button type="submit" class="club-btn-secondary" data-decision="rejectvoid">Reject</button><button type="submit" class="club-btn-primary" data-decision="approvevoid">Approve void</button></div></form></div></div>
<script>const voidModal=document.getElementById('void-review'),voidForm=document.getElementById('void-decision-form');document.querySelectorAll('[data-review]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('void-review-id').value=button.dataset.review;document.getElementById('void-review-reference').textContent=button.dataset.division+' - '+button.dataset.reference;document.getElementById('void-remark').value='';voidModal.hidden=false;}));document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>{button.closest('.popup-overlay').hidden=true;}));voidForm.querySelectorAll('[data-decision]').forEach(button=>button.addEventListener('click',()=>{voidForm.action='<?= ROOT ?>/zonaltreasurer/'+button.dataset.decision;}));</script>
<link rel="stylesheet" href="<?= ROOT ?>/assets/css/club.css">
<?php require __DIR__ . '/../layouts/dashboard-end.view.php'; ?>
