<?php
$escape = static function ($value) { return htmlspecialchars((string)$value, ENT_QUOTES, 'UTF-8'); };
require __DIR__ . '/../partials/icons.view.php';
require __DIR__ . '/../layouts/dashboard-start.view.php';
?>
<section class="club-page" aria-labelledby="coordinator-events-heading">
    <h1 id="coordinator-events-heading" class="sr-only">Approve zonal events</h1>
    <div class="club-stat-grid" aria-label="Zonal event summary"><article class="club-stat-card"><p class="club-stat-label">Submitted events</p><p class="club-stat-value"><?= $escape($eventStats['scheduled'] ?? 0) ?></p></article><article class="club-stat-card"><p class="club-stat-label">Budget committed</p><p class="club-stat-value club-stat-value--small">LKR <?= number_format((float)($eventStats['committed'] ?? 0), 0) ?></p></article><article class="club-stat-card"><p class="club-stat-label">Available event budget</p><p class="club-stat-value club-stat-value--small">LKR <?= number_format((float)($eventStats['available'] ?? 0), 0) ?></p></article></div>
    <?php if ($flash): ?><div class="club-error-banner" role="status"><span class="club-error-icon"><?= yn_icon('info') ?></span><p><?= $escape($flash) ?></p></div><?php endif; ?>
    <section class="club-panel" aria-labelledby="event-queue-heading"><div class="club-panel-header"><div><p class="club-eyebrow">Gampaha Zone</p><h2 id="event-queue-heading">Zonal event approvals</h2></div></div><p class="club-muted">Review events submitted by the Zonal Secretary. A decision remark is required for approval or requested changes.</p><div class="club-list"><?php foreach ($events as $event): ?><article class="club-list-item"><div class="club-list-icon" aria-hidden="true"><?= yn_icon('calendar') ?></div><div class="club-list-copy"><h3><?= $escape($event['title']) ?></h3><p><?= $escape($event['date']) ?>, <?= $escape($event['location']) ?></p><p class="club-event-meta"><?= $escape($event['type']) ?> · LKR <?= number_format($event['budget'], 2) ?> · <?= $escape($event['audience']) ?></p><?php if (!empty($event['coordinator_remark'])): ?><p class="club-note">Coordinator remark: <?= $escape($event['coordinator_remark']) ?></p><?php endif; ?></div><div class="club-event-side"><span class="club-pill club-pill--<?= $event['status'] === 'Pending approval' ? 'pending' : 'approved' ?>"><?= $escape($event['status']) ?></span><?php if ($event['status'] === 'Pending approval'): ?><button class="club-btn-small" type="button" data-review="<?= $escape($event['id']) ?>" data-title="<?= $escape($event['title']) ?>">Review</button><?php endif; ?></div></article><?php endforeach; ?></div></section>
</section>
<div id="event-review" class="popup-overlay" hidden><div class="popup-content club-modal" role="dialog" aria-modal="true" aria-labelledby="event-review-title"><button type="button" class="popup-close" data-close aria-label="Close"><?= yn_icon('close') ?></button><p class="club-eyebrow">Zonal Coordinator decision</p><h2 id="event-review-title">Review event</h2><p id="event-review-name" class="club-sub-note"></p><form id="event-decision" method="post" class="club-form"><input type="hidden" name="csrf_token" value="<?= $escape($csrf_token) ?>"><input type="hidden" id="event-id" name="event_id"><div class="club-field"><label for="event-remark">Decision remark</label><textarea id="event-remark" name="remark" rows="4" maxlength="1000" required></textarea></div><div class="club-modal-footer"><button type="button" class="club-btn-secondary" data-close>Cancel</button><button type="submit" class="club-btn-secondary" data-decision="returnevent">Request changes</button><button type="submit" class="club-btn-primary" data-decision="approveevent">Approve event</button></div></form></div></div>
<script>const modal=document.getElementById('event-review'),form=document.getElementById('event-decision');document.querySelectorAll('[data-review]').forEach(button=>button.addEventListener('click',()=>{document.getElementById('event-id').value=button.dataset.review;document.getElementById('event-review-name').textContent=button.dataset.title;modal.hidden=false;}));document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>{button.closest('.popup-overlay').hidden=true;}));form.querySelectorAll('[data-decision]').forEach(button=>button.addEventListener('click',()=>{form.action='<?= ROOT ?>/zonalcoordinator/'+button.dataset.decision;}));</script>
<link rel="stylesheet" href="<?= ROOT ?>/assets/css/club.css">
<?php require __DIR__ . '/../layouts/dashboard-end.view.php'; ?>
