<?php

final class DivisionalReportPdf {
    private const PAGE_WIDTH = 842.0;
    private const PAGE_HEIGHT = 595.0;
    private const MARGIN = 36.0;

    public static function render(object $report, object $division, array $reportData): string {
        $columns = (array) ($reportData['columns'] ?? []);
        $rows = (array) ($reportData['rows'] ?? []);
        $pages = [];
        $current = self::startPage($report, $division, $reportData, false);
        $y = $current['y'];
        $commands = $current['commands'];
        $columnCount = max(1, count($columns));
        $tableWidth = self::PAGE_WIDTH - (self::MARGIN * 2);
        $columnWidth = $tableWidth / $columnCount;

        if (!$rows) {
            $commands .= self::text(self::MARGIN, $y - 18, 'No records found for the selected reporting period.', 10, false, [0.31, 0.35, 0.43]);
        } else {
            foreach ($rows as $index => $row) {
                $cellLines = [];
                $maximumLines = 1;
                foreach (array_keys($columns) as $key) {
                    $lines = self::wrap((string) ($row[$key] ?? '-'), $columnWidth - 10, 7.2);
                    $cellLines[] = $lines;
                    $maximumLines = max($maximumLines, count($lines));
                }
                $rowHeight = max(22.0, 10.0 + ($maximumLines * 8.2));
                if ($y - $rowHeight < 43) {
                    $pages[] = $commands;
                    $current = self::startPage($report, $division, $reportData, true);
                    $y = $current['y'];
                    $commands = $current['commands'];
                }
                if ($index % 2 === 1) {
                    $commands .= self::fillRect(self::MARGIN, $y - $rowHeight, $tableWidth, $rowHeight, [0.97, 0.98, 1.0]);
                }
                $x = self::MARGIN;
                foreach ($cellLines as $lines) {
                    $commands .= self::strokeRect($x, $y - $rowHeight, $columnWidth, $rowHeight, [0.85, 0.87, 0.91]);
                    $lineY = $y - 12;
                    foreach ($lines as $line) {
                        $commands .= self::text($x + 5, $lineY, $line, 7.2, false, [0.15, 0.18, 0.25]);
                        $lineY -= 8.2;
                    }
                    $x += $columnWidth;
                }
                $y -= $rowHeight;
            }
        }
        $pages[] = $commands;

        $pageCount = count($pages);
        foreach ($pages as $index => &$page) {
            $page .= self::text(
                self::PAGE_WIDTH - self::MARGIN - 82,
                21,
                'Page ' . ($index + 1) . ' of ' . $pageCount,
                7.5,
                false,
                [0.38, 0.42, 0.50]
            );
            $page .= self::text(self::MARGIN, 21, 'Generated from YouthNexus records', 7.5, false, [0.38, 0.42, 0.50]);
        }
        unset($page);

        return self::document($pages);
    }

    private static function startPage(object $report, object $division, array $data, bool $continuation): array {
        $commands = '';
        $commands .= self::fillRect(0, 0, self::PAGE_WIDTH, self::PAGE_HEIGHT, [1, 1, 1]);
        $commands .= self::fillRect(0, self::PAGE_HEIGHT - 8, self::PAGE_WIDTH, 8, [0.12, 0.27, 0.70]);
        $commands .= self::text(self::MARGIN, 552, 'YouthNexus', 10, true, [0.12, 0.27, 0.70]);
        $commands .= self::text(self::MARGIN, 529, (string) $report->type_name, $continuation ? 15 : 18, true, [0.08, 0.10, 0.16]);
        if ($continuation) {
            $commands .= self::text(self::MARGIN, 511, (string) $division->division_name . ' - continued', 8.5, false, [0.38, 0.42, 0.50]);
            $y = 486;
        } else {
            $period = self::date((string) $report->date_range_start) . ' - ' . self::date((string) $report->date_range_end);
            $reference = 'RPT-' . str_pad((string) $report->report_id, 4, '0', STR_PAD_LEFT);
            $generatedBy = trim((string) ($report->generated_by_name ?? '')) ?: 'Divisional Treasurer';
            $commands .= self::text(self::MARGIN, 507, (string) $division->division_name, 9, false, [0.31, 0.35, 0.43]);
            $commands .= self::text(560, 552, $reference, 10, true, [0.08, 0.10, 0.16]);
            $commands .= self::text(560, 535, 'Period: ' . $period, 8, false, [0.31, 0.35, 0.43]);
            $commands .= self::text(560, 520, 'Generated by: ' . $generatedBy, 8, false, [0.31, 0.35, 0.43]);
            $commands .= self::text(560, 505, 'Generated: ' . self::dateTime((string) $report->generated_at), 8, false, [0.31, 0.35, 0.43]);
            $commands .= self::line(self::MARGIN, 487, self::PAGE_WIDTH - self::MARGIN, 487, [0.85, 0.87, 0.91]);

            $kpis = array_values((array) ($data['kpis'] ?? []));
            $gap = 10.0;
            $cardWidth = (self::PAGE_WIDTH - (self::MARGIN * 2) - ($gap * 3)) / 4;
            foreach (array_slice($kpis, 0, 4) as $index => $kpi) {
                $x = self::MARGIN + (($cardWidth + $gap) * $index);
                $commands .= self::fillRect($x, 426, $cardWidth, 47, [0.94, 0.96, 1.0]);
                $commands .= self::text($x + 10, 456, (string) ($kpi['label'] ?? ''), 7.3, false, [0.31, 0.35, 0.43]);
                $commands .= self::text($x + 10, 438, (string) ($kpi['value'] ?? ''), 11, true, [0.08, 0.10, 0.16]);
            }
            $y = 404;
        }

        $columns = (array) ($data['columns'] ?? []);
        if ($columns) {
            $tableWidth = self::PAGE_WIDTH - (self::MARGIN * 2);
            $columnWidth = $tableWidth / count($columns);
            $headerLines = [];
            $maxHeaderLines = 1;
            foreach ($columns as $label) {
                $lines = self::wrap((string) $label, $columnWidth - 10, 7.2);
                $headerLines[] = $lines;
                $maxHeaderLines = max($maxHeaderLines, count($lines));
            }
            $headerHeight = max(24.0, 11.0 + ($maxHeaderLines * 8.2));
            $commands .= self::fillRect(self::MARGIN, $y - $headerHeight, $tableWidth, $headerHeight, [0.12, 0.27, 0.70]);
            $x = self::MARGIN;
            foreach ($headerLines as $lines) {
                $lineY = $y - 13;
                foreach ($lines as $line) {
                    $commands .= self::text($x + 5, $lineY, strtoupper($line), 7.2, true, [1, 1, 1]);
                    $lineY -= 8.2;
                }
                $x += $columnWidth;
            }
            $y -= $headerHeight;
        }

        return ['commands' => $commands, 'y' => $y];
    }

    private static function document(array $pages): string {
        $objects = [];
        $pageIds = [];
        foreach ($pages as $index => $commands) {
            $pageIds[] = 5 + ($index * 2);
        }
        $objects[1] = '<< /Type /Catalog /Pages 2 0 R >>';
        $objects[2] = '<< /Type /Pages /Kids [' . implode(' ', array_map(static fn($id) => $id . ' 0 R', $pageIds)) . '] /Count ' . count($pages) . ' >>';
        $objects[3] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';
        $objects[4] = '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>';
        foreach ($pages as $index => $commands) {
            $pageId = 5 + ($index * 2);
            $contentId = $pageId + 1;
            $objects[$pageId] = '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ' . self::PAGE_WIDTH . ' ' . self::PAGE_HEIGHT . '] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> >> /Contents ' . $contentId . ' 0 R >>';
            $objects[$contentId] = '<< /Length ' . strlen($commands) . " >>\nstream\n" . $commands . "endstream";
        }
        ksort($objects);
        $pdf = "%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";
        $offsets = [0];
        foreach ($objects as $id => $object) {
            $offsets[$id] = strlen($pdf);
            $pdf .= $id . " 0 obj\n" . $object . "\nendobj\n";
        }
        $xref = strlen($pdf);
        $size = max(array_keys($objects)) + 1;
        $pdf .= "xref\n0 " . $size . "\n0000000000 65535 f \n";
        for ($id = 1; $id < $size; $id++) {
            $pdf .= sprintf('%010d 00000 n ', $offsets[$id]) . "\n";
        }
        $pdf .= "trailer\n<< /Size " . $size . " /Root 1 0 R >>\nstartxref\n" . $xref . "\n%%EOF";
        return $pdf;
    }

    private static function text(float $x, float $y, string $value, float $size, bool $bold, array $colour): string {
        $font = $bold ? 'F2' : 'F1';
        return self::colour($colour, 'rg') . " BT /{$font} " . self::number($size) . ' Tf 1 0 0 1 ' . self::number($x) . ' ' . self::number($y) . ' Tm (' . self::escape($value) . ") Tj ET\n";
    }

    private static function fillRect(float $x, float $y, float $width, float $height, array $colour): string {
        return self::colour($colour, 'rg') . ' ' . self::number($x) . ' ' . self::number($y) . ' ' . self::number($width) . ' ' . self::number($height) . " re f\n";
    }

    private static function strokeRect(float $x, float $y, float $width, float $height, array $colour): string {
        return self::colour($colour, 'RG') . ' 0.5 w ' . self::number($x) . ' ' . self::number($y) . ' ' . self::number($width) . ' ' . self::number($height) . " re S\n";
    }

    private static function line(float $x1, float $y1, float $x2, float $y2, array $colour): string {
        return self::colour($colour, 'RG') . ' 0.5 w ' . self::number($x1) . ' ' . self::number($y1) . ' m ' . self::number($x2) . ' ' . self::number($y2) . " l S\n";
    }

    private static function wrap(string $value, float $width, float $fontSize): array {
        $value = trim((string) preg_replace('/\s+/u', ' ', $value));
        if ($value === '') return ['-'];
        $characters = max(4, (int) floor($width / ($fontSize * 0.53)));
        return explode("\n", wordwrap($value, $characters, "\n", true));
    }

    private static function escape(string $value): string {
        $value = str_replace(["\r", "\n", "\t"], ' ', $value);
        if (function_exists('iconv')) {
            $converted = iconv('UTF-8', 'Windows-1252//TRANSLIT//IGNORE', $value);
            if ($converted !== false) $value = $converted;
        } else {
            $value = preg_replace('/[^\x20-\x7E]/', '', $value) ?? '';
        }
        return str_replace(['\\', '(', ')'], ['\\\\', '\\(', '\\)'], $value);
    }

    private static function colour(array $colour, string $operator): string {
        return implode(' ', array_map([self::class, 'number'], $colour)) . ' ' . $operator;
    }

    private static function number(float $value): string {
        return rtrim(rtrim(number_format($value, 3, '.', ''), '0'), '.');
    }

    private static function date(string $value): string {
        $timestamp = strtotime($value);
        return $timestamp ? date('d M Y', $timestamp) : $value;
    }

    private static function dateTime(string $value): string {
        $timestamp = strtotime($value);
        return $timestamp ? date('d M Y, H:i', $timestamp) : $value;
    }
}
